---
#Setup monit
- name: Install monit
  apt:
      name: "{{ item }}"
      state: latest
      force: yes
  with_items:
    - monit
    - python3-yaml
  notify: Restart monit

- name: Configure monitrc
  template:
      backup: yes
      mode: 0600
      owner: root
      group: root
      src: "monit_config"
      dest: "/etc/monit/monitrc"
  notify: Restart monit

- name: Monitor basics
  template:
      src: "basic/{{ item }}"
      dest: "/etc/monit/conf.d/{{ item }}"
      owner: root
      group: root
  with_items: "{{ monit_basic_configs }}"
  when: monit_basic_configs is defined
  notify: Restart monit

- name: Monitor http watch
  template:
      src: "httpTest"
      dest: "/etc/monit/conf.d/httpTest"
      owner: root
      group: root
  notify: Restart monit
  when: monit_watched_hosts is defined

- include: twilio.yml
  when: "{{ monit_twilio }}"
