---
#Setup monit
- name: Install monit - Debian
  apt:
      name: "{{ item }}"
      state: latest
      force: yes
  with_items:
    - monit
    - python3-yaml
  notify: Restart monit
  when: ansible_os_family == "Debian"

- name: Install monit - Archlinux
  pacman:
    state: latest
    name: "{{ item }}"
  with_items:
    - monit
    - python-yaml
  when: ansible_os_family == "Archlinux"

- name: Configure monitrc
  template:
      backup: yes
      mode: 0600
      owner: root
      group: root
      src: "monit_config"
      dest: "{{ monit_main_config}}"
  notify: Restart monit

- name: Make monit conf directory
  file:
    path: "{{ monit_conf_dir }}"
    state: directory

- name: Monitor basics
  template:
      src: "basic/{{ item }}"
      dest: "{{ monit_conf_dir }}/{{ item }}"
      owner: root
      group: root
  with_items: "{{ monit_basic_configs|default(omit) }}"
  when: monit_basic_configs is defined
  notify: Restart monit

- name: Monitor custom
  template:
      src: "{{ conf_dir }}/etc/monit/monit.d/{{ item }}"
      dest: "{{ monit_conf_dir }}/{{ item }}"
      owner: root
      group: root
  with_items: "{{ monit_custom_configs|default(omit) }}"
  when: monit_custom_configs is defined
  notify: Restart monit

- name: Generate monit ssl cert
  command: openssl req -new -x509 -days 365 -nodes -newkey rsa:4096 -keyout {{ monit_mmonit_pemfile}} -out {{ monit_mmonit_pemfile }} -subj "/C=SI/ST=Slovenia/L=Ljubljana/O=Izzivizzi/OU=devops/CN={{ ansible_hostname }}"

- name: Set monit SSL cert permissions
  file:
    mode: 0700
    owner: root
    group: root
    path: /opt/certs/monit.pem

- name: Monitor http watch
  template:
      src: "httpTest"
      dest: "/etc/monit/conf.d/httpTest"
      owner: root
      group: root
  notify: Restart monit
  when: monit_watched_hosts is defined

- include: twilio.yml
  when: "{{ monit_twilio }}"
