---
#Setup monit
- name: Install monit
  apt:
      name: "{{ item }}"
      state: latest
      force: yes
  with_items:
    - monit
    - python3-yaml
  notify: Restart monit

- name: Configure monitrc
  template:
      backup: yes
      mode: 0600
      owner: root
      group: root
      src: "monit_config"
      dest: "/etc/monit/monitrc"
  notify: Restart monit

- name: Monitor basics
  template:
      src: "basic/{{ item }}"
      dest: "/etc/monit/conf.d/{{ item }}"
      owner: root
      group: root
  with_items: "{{ monit_basic_configs }}"
  when: monit_basic_configs is defined
  notify: Restart monit

- name: Generate monit ssl cert
  command: openssl req -new -x509 -days 365 -nodes -newkey rsa:4096 -keyout {{ monit_mmonit_pemfile}} -out {{ monit_mmonit_pemfile }} -subj "/C=SI/ST=Slovenia/L=Ljubljana/O=Izzivizzi/OU=devops/CN={{ ansible_hostname }}"

- name: Set monit SSL cert permissions
  file:
    mode: 0700
    owner: root
    group: root
    path: /opt/certs/monit.pem

- name: Monitor http watch
  template:
      src: "httpTest"
      dest: "/etc/monit/conf.d/httpTest"
      owner: root
      group: root
  notify: Restart monit
  when: monit_watched_hosts is defined

- include: twilio.yml
  when: "{{ monit_twilio }}"
